spring.application.name=airBnbApp
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/airBnb

spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format.sql=true

server.servlet.context-path=/api/v1

jwt.secretKey="your_super_secret_key_here";


frontend.url=http://localhost:8080

stripe.secret.key=sk_test_yourStripeSecretKey

stripe.webhook.secret=write_your_stripe_webhook_secret_key_here